version: '3'

volumes:
  postgres_data: {}
  media_files: {}

services:

  redis:
    image: redis
    restart: unless-stopped

  database:
    image: postgres:alpine
    restart: unless-stopped
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
    environment:
      - 'POSTGRES_PASSWORD=123'

  webapp:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    depends_on:
      - redis
      - database
    command: /bin/sh /app/docker/start.sh
    entrypoint: /app/docker/entrypoint.sh
    env_file:
      - .env
    volumes:
      - 'media_files:/app/source/media/'
    ports:
      - 8000:8000
