# Generated by Django 2.2.6 on 2019-11-04 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default=1, max_length=155),
            preserve_default=False,
        ),
    ]
