# Generated by Django 2.2.6 on 2019-11-03 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_article_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
