# Generated by Django 2.2.7 on 2019-11-05 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_article_is_draft'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='is_draft',
            new_name='is_published',
        ),
    ]
