# Generated by Django 2.2.7 on 2019-11-09 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
